"use strict";(()=>{var e={};e.id=826,e.ids=[826],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},27790:e=>{e.exports=require("assert")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},17702:e=>{e.exports=require("events")},32615:e=>{e.exports=require("http")},35240:e=>{e.exports=require("https")},86624:e=>{e.exports=require("querystring")},17360:e=>{e.exports=require("url")},21764:e=>{e.exports=require("util")},71568:e=>{e.exports=require("zlib")},92565:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>x,patchFetch:()=>f,requestAsyncStorage:()=>c,routeModule:()=>d,serverHooks:()=>g,staticGenerationAsyncStorage:()=>h});var a={};r.r(a),r.d(a,{POST:()=>u,dynamic:()=>m});var s=r(79182),o=r(72007),n=r(56719),i=r(93442),p=r(15649),l=r(11826);let m="force-dynamic";async function u(e){try{let t=await (0,p.getServerSession)(l.L);if(!t?.user)return i.NextResponse.json({error:"Unauthorized"},{status:401});let{prompt:r,type:a}=await e.json();if(!r||!a)return i.NextResponse.json({error:"Missing prompt or type"},{status:400});let s="image"===a?`You are an expert AI image generation prompt engineer. Your task is to enhance user prompts to create stunning, viral-worthy Instagram content. 

Transform the user's simple prompt into a detailed, compelling prompt that will generate amazing results. Include:
- Visual style and aesthetics
- Lighting and atmosphere
- Colors and mood
- Composition details
- Quality keywords (8k, ultra detailed, professional, etc.)

Keep it concise but powerful. Return ONLY the enhanced prompt text, no explanations.`:`You are an expert AI video generation prompt engineer. Your task is to enhance user prompts to create engaging, viral Instagram Reels.

Transform the user's simple prompt into a detailed video animation prompt. Include:
- Motion and animation style
- Camera movements
- Transitions and effects
- Mood and pacing
- Duration considerations (15-30 seconds ideal for Reels)

Keep it concise but powerful. Return ONLY the enhanced prompt text, no explanations.`,o=await fetch("https://apps.abacus.ai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${process.env.ABACUSAI_API_KEY}`},body:JSON.stringify({model:"gpt-4.1-mini",messages:[{role:"system",content:s},{role:"user",content:`Original prompt: ${r}`}],max_tokens:300,temperature:.7})});if(!o.ok)throw Error("Failed to enhance prompt");let n=await o.json(),m=n.choices[0]?.message?.content||r;return i.NextResponse.json({enhancedPrompt:m})}catch(e){return console.error("Enhance prompt error:",e),i.NextResponse.json({error:"Failed to enhance prompt"},{status:500})}}let d=new s.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/enhance-prompt/route",pathname:"/api/enhance-prompt",filename:"route",bundlePath:"app/api/enhance-prompt/route"},resolvedPagePath:"/home/ubuntu/instagram_content_generator/nextjs_space/app/api/enhance-prompt/route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:c,staticGenerationAsyncStorage:h,serverHooks:g}=d,x="/api/enhance-prompt/route";function f(){return(0,n.patchFetch)({serverHooks:g,staticGenerationAsyncStorage:h})}},11826:(e,t,r)=>{r.d(t,{L:()=>p});var a=r(64617),s=r(66291),o=r(3390),n=r.n(o),i=r(35970);let p={adapter:(0,a.N)(i._),session:{strategy:"jwt"},pages:{signIn:"/auth/login"},providers:[(0,s.Z)({name:"credentials",credentials:{email:{label:"Email",type:"email"},password:{label:"Password",type:"password"}},async authorize(e){if(!e?.email||!e?.password)throw Error("Email et mot de passe requis");let t=await i._.user.findUnique({where:{email:e.email}});if(!t||!await n().compare(e.password,t.password||""))throw Error("Email ou mot de passe incorrect");if(!t.isApproved)throw Error("Votre compte n'a pas encore \xe9t\xe9 approuv\xe9 par l'administrateur. Veuillez patienter.");return{id:t.id,email:t.email,name:t.name||`${t.firstName||""} ${t.lastName||""}`.trim(),firstName:t.firstName,lastName:t.lastName,role:t.role,isApproved:t.isApproved}}})],callbacks:{session:({session:e,token:t})=>({...e,user:{...e.user,id:t.id,firstName:t.firstName,lastName:t.lastName,role:t.role,isApproved:t.isApproved}}),jwt:({token:e,user:t})=>t?{...e,id:t.id,firstName:t.firstName,lastName:t.lastName,role:t.role,isApproved:t.isApproved}:e}}},35970:(e,t,r)=>{r.d(t,{_:()=>s});let a=require("@prisma/client"),s=globalThis.prisma??new a.PrismaClient}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[372,329,511,609],()=>r(92565));module.exports=a})();